### PR TITLE
PR JavaScript: Restaurant Page

### PR DESCRIPTION
**Pull request by pastorp3**
This is Project #2 in the JavaScript V1.1 curriculum. The purpose of the project is to create a restaurant page in which all the content is generated via JavaScript modules. The features implemented in this project were:

- Created the src folder to host all the files necessary for the creation of the page: CSS files and js modules created.
- Created the dist folder to tell webpack where to store the final assets and files for the bundle run.
- Use DOM manipulation to create the content inside each navigation tab.
- Loaders used from Webpack:
- style and css for CSS files.
- file for images
- image-webpack for image compression.

### CODE REVIEW

**Comment by sumancrest0001** [comment]
Status: changes required :gear:
Hello @pastorp3, you have done a nice work and we are almost done. Some minor changes are required to get mastery. Let's consider the following points.
[required] We have to add the node_modules folder into the .gitignore file.
[Required] PR could have been more descriptive.
[Required] How can I run the project? No script to run the project. [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/scripts_requirement.png)
[Required] Please add all the instructions to clone and run the project on local machine.
[Optional] CSS file can be added to the source and bundled using Webpack.

**Review by sumancrest0001 — CHANGES_REQUESTED** [review]
**Please make the necessary changes and send for another review. If you have any query feel free to message me on slack Suman Shrestha
Happy coding !!!**

**Comment by pastorp3** [comment]
- add node_modules to .gitignore 
- Add description to PR
-Add instructions to Readme file

**Review by wathigo — CHANGES_REQUESTED** [review]
### Changes Required :heavy_multiplication_x: 
Great job implementing the suggested changes.
Let's make some changes before we move on.

**REQUIRED**
* Let's delete the `node_modules` folder and commit the changes since it should not be committed. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from Pathwright).
* Let's add the basic webpack run command in the scripts section of our `package.json`.
```javascript
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
```
([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/scripts_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622983/)).
* We have some grammatical errors n our README file. Check the section about running the project locally.

**After making the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo.**

**Comment by pastorp3** [comment]
-delete node_modules

- add run command to package.json

**Comment by Dandush03** [comment]
# Status: :rocket: Project Approved :rocket: 

### Great Work! Keep It Up :muscle: 

# Happy Coding! :nerd_face: :computer:

**Review by Dandush03 — APPROVED** [review]
# Status: :rocket: Project Approved :rocket: 

### Great Work! Keep It Up :muscle: 

# Happy Coding! :nerd_face: :computer:

**Pull request merged**
